### ISSUE TITLE
graphql dependency

### ISSUE THREAD

**Issue by PowerMogli** [feathers-plus/feathers-hooks-common#487] opened 2018-12-18 13:37 UTC
Correct me, but should not graphql module be a dependency of feathers-hooks-common instead of devDependency?!

Because we now get build errors in our typescript project. It tells us the following:

```
node_modules/feathers-hooks-common/types/index.d.ts(5,60): error TS2307: Cannot find module 'graphql'
```

**Comment by eddyystop** [comment] 2018-12-18 18:53
I know of no feathers-hooks-common hook that calls feathers-graphql nor graphql/graphql. They are only used in testing.

So if there's a TS issue I would think its with the typings rather than the dependencies.  

@j2L4e ^^^

**Comment by PowerMogli** [comment] 2018-12-19 07:36
> I know of no feathers-hooks-common hook that calls feathers-graphql nor graphql/graphql. They are only used in testing.
> 
> So if there's a TS issue I would think its with the typings rather than the dependencies.
> 
> @j2L4e ^^^

Please fix it, otherwise we can not use it in our TS projects.

**Comment by j2L4e** [comment] 2018-12-19 09:08
Making it a depebdency is the correct fix. @powermogli, would you please submit a PR?

**Comment by cawel** [comment] 2019-01-01 19:44
In the `master` branch, `graphql` is no longer a dev dependency but a dependency ([see commit](https://github.com/feathers-plus/feathers-hooks-common/commit/1cd2bd8fe3e000ca0d0eafeb349b476a74f27cb3) from @PowerMogli on Dec 19). 

I believe we just need to bump the version to `4.19.7` so that we can take advantage of the fix.

**Comment by eddyystop** [comment] 2019-01-01 19:59
@j2L4e no where in the repo that I know of is feathers-graphql or graphql called directly. That makes graphql a devDependency not a dependency.

What is the issue regarding this in the typings?

**Comment by cawel** [comment] 2019-01-01 22:15
@eddyystop The issue is related to TypeScript. Both @PowerMogli and I have this build error:

```
node_modules/feathers-hooks-common/types/index.d.ts:5:60 - error TS2307: Cannot find module 'graphql'.

5 import { GraphQLSchema, parse, GraphQLFieldResolver } from 'graphql';
```

Indeed, line 5 of `feathers-hooks-common/types/index.d.ts` is trying to import `graphql`

**Comment by cawel** [comment] 2019-01-02 05:59
A better solution is probably to add the `graphql` types:

`npm install --save-dev @types/graphql`

and then I had to tweak my tsconfig by adding a compiler option:

```javascript
"compilerOptions": {
  "lib": ["esnext"]
}
```

Otherwise I had TS complaining it could not find 'AsyncIterator'.

**Comment by eddyystop** [comment] 2019-01-02 14:20
I don't handle TS.

Let's see if @j2L4e can fix this today. Otherwise could you perhaps submit a PR later in the day?

**Comment by eddyystop** [comment] 2019-01-03 02:14
@cawel could you create a PR please?

**Comment by eddyystop** [comment] 2019-01-04 23:33
Resolved via https://github.com/feathers-plus/feathers-hooks-common/pull/496 .

**Closed by eddyystop** 2019-01-04 23:33 UTC
Labels: awaiting response
